# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npx run-s --print-label build:* 2> $GITHUB_WORKSPACE/build.stderr.log
      - run: npx run-s --print-label test:* 2> $GITHUB_WORKSPACE/test.stderr.log

      - run: |
          npx sass src/第8章_Tailwind_CSSを既存のプロジェクトに導入する/sass/ok.scss
          ! npx sass src/第8章_Tailwind_CSSを既存のプロジェクトに導入する/sass/ng.scss

          npx lessc src/第8章_Tailwind_CSSを既存のプロジェクトに導入する/less/ok.less
          ! npx lessc src/第8章_Tailwind_CSSを既存のプロジェクトに導入する/less/ng.less

          npx stylus src/第8章_Tailwind_CSSを既存のプロジェクトに導入する/sass/ok.styl
          ! npx stylus src/第8章_Tailwind_CSSを既存のプロジェクトに導入する/sass/ng.styl

      - run: |
          if grep "warn" $GITHUB_WORKSPACE/*.log; then
            echo 'Looks like tailwind build has unexpected warnings'
            exit 1
          fi
